Add equality comparison operators to Query and underlying required objects
open-rmf/rmf_traffic pull request #3
Opened 2021-03-08 03:34 UTC by gbiggs

## New feature implementation

### Equality comparison operators for Query

This PR adds the equal and not-equal operators to the schedule `Query` object.
It also adds them to all objects used internally (recursive) by `Query`.
This allows `Query`s to be directly compared for equality, which supports operations such as identifying if two schedule mirrors are requesting the same query.

### Implementation description

In general, the operators are implemented by member-wise comparisons of each object's members.
Shapes are a special case.
A template function and a "register" function are used to reduce the amount of code that needs to be added for each new shape type.

All not-equals operators are implemented as the inverse of the equality operators to reduce the code that must be maintained.

2021-03-26 09:01 UTC, mxgrey requested changes
This is generally looking really good!

I have a few nitpick requests, and then there's one actually important request regarding the `Timespan` comparison. I've pushed a unit test that shows the `Timespan` comparison currently failing for an edge case.

I've also merged in the latest `main` which introduces code linting, and some of the changes in this PR are violating the style guide, particularly for line length.

2021-03-30 04:56 UTC, gbiggs commented on rmf_traffic/include/rmf_traffic/geometry/Shape.hpp
> +std::function<bool(const Shape& other)> make_equality_comparitor(const T& myself)
Fixed in d7de03f7dd3880b4bfbfb84f2221c4c0cee21e56.

2021-03-30 06:34 UTC, gbiggs commented on rmf_traffic/test/unit/schedule/test_Query.cpp
> +      REQUIRE(query1 == query2);
Done in 26a7cf0.

2021-03-30 06:34 UTC, gbiggs commented on rmf_traffic/include/rmf_traffic/geometry/Shape.hpp
> +std::function<bool(const Shape& other)> make_equality_comparitor(const T& myself)
Done in d7de03f7dd3880b4bfbfb84f2221c4c0cee21e56.

2021-03-30 06:35 UTC, gbiggs commented on rmf_traffic/src/rmf_traffic/schedule/Query.cpp
> +  return lhs.maps() == rhs.maps() &&
Done in f13acda.

2021-03-30 07:31 UTC, mxgrey approved these changes
This looks good! It seems there are just some style complaints from uncrustify to fix.

2021-03-30 07:31 UTC, merged